// built-ins
const util = require('util')
const wait = util.promisify(setTimeout)

// npm modules
const inquirer = require('inquirer')
const callbackGrowl = require('growl')
const growl = util.promisify(callbackGrowl)
const dnd = require('@sindresorhus/do-not-disturb')
const ora = require('ora')
require('loud-rejection/register')

const growlArgs = {
  title: 'loops',
  name: 'loops',
  sticky: true,
  sound: 'pop',
  priority: 2
}

const workLoop = async (answers) => {
  const spinner = ora('Working...').start()
  // calling workLoop turns on do not disturb, which hides the notification generated by breakLoop
  // so, let's wait 5 seconds after we start "working" to enable DND and thus hide the notification
  setTimeout(dnd.enable, 5000)
  await wait(parseFloat(answers.workLength)*60*1000)
  spinner.succeed('Worked.')
  await dnd.disable()
  await growl('Work loop complete! Time to reflect.', growlArgs)
}

const reflection = async () => {
  const answers = await inquirer.prompt([
    {
      type: 'input',
      name: 'todo',
      message: 'What new things do you need to do?'
    }
  ])
}

const breakLoop = async (answers) => {
  const spinner = ora('Relaxing...').start()
  await wait(parseFloat(answers.breakLength)*60*1000)
  spinner.succeed('Relaxed.')
  await dnd.disable()
  console.log('Do not disturb is:', await dnd.isEnabled())
  await (new Promise((resolve) => growl('Break complete! Time to start another loop.', growlArgs, resolve)))
}

const main = async () => {
  const answers = await inquirer.prompt([
    {
      type: 'input',
      name: 'workLength',
      message: 'How many minutes long should the work units be?',
      default: '30',
      validate: (input) => isNaN(parseFloat(input)) ? 'Please input a number.' : true
    },
    {
      type: 'input',
      name: 'breakLength',
      message: 'How many minutes long should the breaks between work units be?',
      default: '4',
      validate: (input) => isNaN(parseFloat(input)) ? 'Please input a number.' : true
    },
    {
      type: 'confirm',
      name: 'enableSuperBreaks',
      message: 'Do you want to take a longer break every few breaks?',
      default: true
    },
    {
      type: 'list',
      name: 'superBreakModulo',
      message: 'How often do you want to take a longer break?',
      default: 2,
      when: (answers) => { return answers.enableSuperBreaks },
      choices: [
        {
          name: 'Every other break',
          short: 'Every other',
          value: 2
        },
        {
          name: 'Every third break',
          short: 'Every third',
          value: 3
        },
        {
          name: 'Every fourth break',
          short: 'Every fourth',
          value: 4
        },
        {
          name: 'Every fifth break',
          short: 'Every fifth',
          value: 5
        }
      ]
    },
    {
      type: 'input',
      name: 'superBreakLength',
      message: 'How many minutes long should a long break be?',
      default: '30',
      when: (answers) => answers.enableSuperBreaks,
      validate: (input) => isNaN(parseFloat(input)) ? 'Please input a number.' : true
    }
  ])

  if(process.env.debug) {
    console.log(JSON.stringify(answers, null, 2))
  }

  while(true) {
    await workLoop(answers)
    await reflection()
    await breakLoop(answers)
  }
}

main()
